dirs:
  data: "test_data/fastq"
  output: "test_data/test_out"
  targets: "test_data/genomes/pcv.fasta"

input:
  format: "fastq"
  paired: True

samples:
  test-B: ["testB_1.fastq","testB_2.fastq"]
  test-A: ["testA_1.fastq","testA_2.fastq"]
