io:
  download: False
  file_list: "test_data/samples.csv"
#  format: "fastq"
  paired: True
  data: "test_data/fastq"
  output: "test_data/output"

align:
  targets: "test_data/genomes/pcv.fasta"

samples:
#  test-B: ["https://github.com/louiejtaylor/viruSnake/blob/master/test_data/fastq/gz/test-B_1.fastq.gz?raw=true","https://github.com/louiejtaylor/viruSnake/blob/master/test_data/fastq/gz/test-B_2.fastq.gz?raw=true"]
#  test-A: ["https://github.com/louiejtaylor/viruSnake/blob/master/test_data/fastq/gz/test-A_1.fastq.gz?raw=true","https://github.com/louiejtaylor/viruSnake/blob/master/test_data/fastq/gz/test-A_2.fastq.gz?raw=true"]

  test-B: ["test-B_1.fastq","test-B_2.fastq"]
  test-A: ["test-A_1.fastq","test-A_2.fastq"]
