io:
  download: True
  file_list: "test_data/samples.csv"
#  format: "fastq"
  paired: True
  data: "test_data/fastq"
  output: "test_data/output"

align:
  targets: "test_data/genomes/pcv.fasta"

samples:
  test-B: ["test-B_1","test-B_2"]
  test-A: ["test-A_1","test-A_2"]
#
#  test-B: ["test-B_1.fastq","test-B_2.fastq"]
#  test-A: ["test-A_1.fastq","test-A_2.fastq"]
