io:
  # directories
  data: "/home/chgu/projects/micu/bsi/ref_meta/Ecoli/hisss/data"
  output: "/home/chgu/projects/micu/bsi/ref_meta/Ecoli/hisss/results"

  # options
  download: False
  paired: True


align:
  tar_dir: "/home/chgu/projects/micu/bsi/ref_meta/Ecoli/hisss/ref"

bcf:
  filter: "DP>7&QUAL>30&MQ>14"

samples:
  SEP031_43691: ['SEP031_43691_1.fastq.gz', 'SEP031_43691_2.fastq.gz']
  CORE0396_44148: ['CORE0396_44148_1.fastq.gz', 'CORE0396_44148_2.fastq.gz']
  chr050unk_44344: ['chr050unk_44344_1.fastq.gz', 'chr050unk_44344_2.fastq.gz']
  SEP030_43616: ['SEP030_43616_1.fastq.gz', 'SEP030_43616_2.fastq.gz']
