io:
  # directories
  data: "/home/chgu/projects/micu/bsi/ref_meta/Axylosxidans/hisss/data"
  output: "/home/chgu/projects/micu/bsi/ref_meta/Axylosxidans/hisss/results"

  # options
  download: False
  paired: True

align:
  targets: "/home/chgu/projects/micu/bsi/ref_meta/Axylosxidans/hisss/all_ref.fasta"

