io:
  # directories
  data: "/home/chgu/projects/micu/bsi/ref_meta/Paeruginosa/hisss/data"
  output: "/home/chgu/projects/micu/bsi/ref_meta/Paeruginosa/hisss/results"

  # options
  download: False
  paired: True


align:
  tar_dir: "/home/chgu/projects/micu/bsi/ref_meta/Paeruginosa/hisss/ref"

bcf:
  filter: "DP>7&QUAL>30&MQ>14"

samples:
  chr047_44315: ['chr047_44315_1.fastq.gz', 'chr047_44315_2.fastq.gz']
  chr055_44343: ['chr055_44343_1.fastq.gz', 'chr055_44343_2.fastq.gz']
  chr052_44336: ['chr052_44336_1.fastq.gz', 'chr052_44336_2.fastq.gz']
  chr052_44323: ['chr052_44323_1.fastq.gz', 'chr052_44323_2.fastq.gz']
