io:
  # directories
  data: "/home/chgu/projects/micu/bsi/ref_meta/Pmirabilis/hisss/data"
  output: "/home/chgu/projects/micu/bsi/ref_meta/Pmirabilis/hisss/results"

  # options
  download: False
  paired: True


align:
  tar_dir: "/home/chgu/projects/micu/bsi/ref_meta/Pmirabilis/hisss/ref"

bcf:
  filter: "DP>7&QUAL>30&MQ>14"

samples:
  chr018_44288: ['chr018_44288_1.fastq.gz', 'chr018_44288_2.fastq.gz']
  chr018_44299: ['chr018_44299_1.fastq.gz', 'chr018_44299_2.fastq.gz']
  chr018_44291: ['chr018_44291_1.fastq.gz', 'chr018_44291_2.fastq.gz']
  chr018_44281: ['chr018_44281_1.fastq.gz', 'chr018_44281_2.fastq.gz']
  chr018_44271: ['chr018_44271_1.fastq.gz', 'chr018_44271_2.fastq.gz']
