io:
  # directories
  data: "/home/chgu/projects/micu/bsi/ref_meta/Axylosxidans/hisss/data"
  output: "/home/chgu/projects/micu/bsi/ref_meta/Axylosxidans/hisss/results"

  # options
  download: False
  paired: True


align:
  tar_dir: "/home/chgu/projects/micu/bsi/ref_meta/Axylosxidans/hisss/ref"

bcf:
  filter: "DP>7&QUAL>30&MQ>14"

samples:
  chr048_44309: ['chr048_44309_1.fastq.gz', 'chr048_44309_2.fastq.gz']
