io:
  # directories
  data: "/home/chgu/projects/micu/bsi/ref_meta/Saerues/hisss/data"
  output: "/home/chgu/projects/micu/bsi/ref_meta/Saerues/hisss/results"

  # options
  download: False
  paired: True


align:
  tar_dir: "/home/chgu/projects/micu/bsi/ref_meta/Saerues/hisss/ref"

bcf:
  filter: "DP>7&QUAL>30&MQ>14"

samples:
  chr054_44341: ['chr054_44341_1.fastq.gz', 'chr054_44341_2.fastq.gz']
  chr051_44321: ['chr051_44321_1.fastq.gz', 'chr051_44321_2.fastq.gz']
