io:
  # directories
  data: "/home/chgu/projects/micu/bsi/ref_meta/Paeruginosa/hisss/data"
  output: "/home/chgu/projects/micu/bsi/ref_meta/Paeruginosa/hisss/results"

  # options
  download: False
  paired: True


align:
  tar_dir: "/home/chgu/projects/micu/bsi/ref_meta/Paeruginosa/hisss/ref"

bcf:
  filter: "DP>7&QUAL>30&MQ>14"

samples:
  chr052_44336_S186: ['chr052_44336_S186_L001_R1_001.fastq.gz', 'chr052_44336_S186_L001_R2_001.fastq.gz']
  chr047_44315_S67: ['chr047_44315_S67_L001_R1_001.fastq.gz', 'chr047_44315_S67_L001_R2_001.fastq.gz']
  chr055_44343_S172: ['chr055_44343_S172_L001_R1_001.fastq.gz', 'chr055_44343_S172_L001_R2_001.fastq.gz']
  chr052_44323_S73: ['chr052_44323_S73_L001_R1_001.fastq.gz', 'chr052_44323_S73_L001_R2_001.fastq.gz']
