io:
  # directories
  data: "/home/chgu/projects/micu/bsi/ref_meta/Smarcescens/hisss/data"
  output: "/home/chgu/projects/micu/bsi/ref_meta/Smarcescens/hisss/results"

  # options
  download: False
  paired: True


align:
  tar_dir: "/home/chgu/projects/micu/bsi/ref_meta/Smarcescens/hisss/ref"

bcf:
  filter: "DP>7&QUAL>30&MQ>14"

samples:
  chr033_44303: ['chr033_44303_1.fastq.gz', 'chr033_44303_2.fastq.gz']
  chr033_44280: ['chr033_44280_1.fastq.gz', 'chr033_44280_2.fastq.gz']
